version: "3"
services:
  api:
    image: classified-api
    build:
      dockerfile: ops/api/Dockerfile
      context: .
    volumes:
      - ./:/app
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    ports:
      - "5000:5000"