version: "3"
services:
  api:
    image: classified-api
    build:
      dockerfile: ops/api/Dockerfile
      context: .
    environment:
      - FLASK_APP=bremen_classifieds_api.bin.api.app
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    depends_on:
      - db

  worker:
    image: classified-api
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
    environment:
      - C_FORCE_ROOT=1
    command: sh -c 'wait-for db:3306 -t 60 -- celery -A bremen_classifieds_api.bin.tasks worker --loglevel=INFO'

  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./ops/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=classifieds
      - MYSQL_USER=classifieds
      - MYSQL_PASSWORD=classifieds
      - MYSQL_ROOT_PASSWORD=classifieds-root
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"