version: "3"
services:
  api:
    image: classified-api
    build:
      dockerfile: ops/api/Dockerfile
      context: .
    environment:
      - FLASK_APP=bremen_classifieds_api.bin.api.app
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./ops/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=classifieds
      - MYSQL_USER=classifieds
      - MYSQL_PASSWORD=classifieds
      - MYSQL_ROOT_PASSWORD=classifieds-root
    ports:
      - "3306:3306"